#!/usr/bin/env python3
"""Backtest Entry Band shadow candidates from verification.json files.

This script does not parse verification.md. It reads machine data generated by
generate_verification_json.py and compares candidate entry bands such as:

  MA20_ZONE / MA10_ZONE / MA5_ZONE / OPEN_CONFIRM

For each band it reports:
  - touch rate
  - hold-to-close quality after touch
  - MAE risk after touch
  - missed upside when not touched and stock rose
  - avoided loss when not touched and stock fell
  - ZoneScore, a regime-weighted row-level score

Usage:
  python entry_band_shadow_backtest.py
  python entry_band_shadow_backtest.py --since 2026-07-06
  python entry_band_shadow_backtest.py --json
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import statistics as st
import sys
from collections import defaultdict
from typing import Any

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8")


REGIME_WEIGHTS = {
    # Strong markets punish missed upside more than drawdown, within reason.
    "strong-sector": {"miss": 1.20, "risk": 0.60, "avoid": 0.30},
    "strong": {"miss": 1.20, "risk": 0.60, "avoid": 0.30},
    # Neutral markets balance opportunity and drawdown.
    "neutral": {"miss": 0.80, "risk": 0.80, "avoid": 0.50},
    "unknown": {"miss": 0.80, "risk": 0.80, "avoid": 0.50},
    # Weak markets value capital protection more.
    "weak": {"miss": 0.40, "risk": 1.20, "avoid": 0.80},
    "panic": {"miss": 0.30, "risk": 1.50, "avoid": 1.00},
}


def fnum(value: Any) -> float | None:
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    try:
        return float(str(value).strip().replace("%", ""))
    except ValueError:
        return None


def mean(values: list[float]) -> float | None:
    return st.mean(values) if values else None


def median(values: list[float]) -> float | None:
    return st.median(values) if values else None


def fmt(value: float | None, suffix: str = "%", width: int = 6) -> str:
    if value is None:
        return " " * (width - 1) + "-"
    return f"{value:{width}.2f}{suffix}"


def pct(n: int, d: int) -> float:
    return n / d * 100 if d else 0.0


def regime_weights(regime: str) -> dict[str, float]:
    return REGIME_WEIGHTS.get(regime, REGIME_WEIGHTS["unknown"])


def row_score(band: dict[str, Any], regime: str) -> float | None:
    """Regime-weighted score for one stock-band observation."""
    if not band.get("enabled"):
        return None
    w = regime_weights(regime)
    touched = band.get("touched")
    if touched is True:
        hold = fnum(band.get("hold_pct")) or 0.0
        mae = fnum(band.get("mae_pct")) or 0.0
        return hold - w["risk"] * abs(min(mae, 0.0))
    if touched is False:
        missed = fnum(band.get("missed_upside_pct"))
        avoided = fnum(band.get("avoided_loss_pct"))
        if missed is not None:
            return -w["miss"] * missed
        if avoided is not None:
            return w["avoid"] * avoided
        return 0.0
    return None


def load_rows(files: list[str]) -> tuple[list[dict[str, Any]], list[str]]:
    rows: list[dict[str, Any]] = []
    warnings: list[str] = []
    for fp in files:
        try:
            with open(fp, encoding="utf-8") as f:
                doc = json.load(f)
        except Exception as exc:  # noqa: BLE001 - backtest should continue
            warnings.append(f"{fp}: json_load_failed: {exc}")
            continue
        date = doc.get("date") or os.path.basename(os.path.dirname(fp))
        regime = doc.get("market", {}).get("regime_hint") or "unknown"
        for stock in doc.get("stocks", []):
            code = stock.get("code")
            strategy = stock.get("strategy")
            bands = stock.get("shadow_bands") or {}
            for band_name, band in bands.items():
                if not isinstance(band, dict):
                    continue
                score = row_score(band, regime)
                if score is None:
                    continue
                rows.append({
                    "date": date,
                    "regime": regime,
                    "code": code,
                    "strategy": strategy or "unknown",
                    "band": band_name,
                    "touched": band.get("touched"),
                    "hold_pct": fnum(band.get("hold_pct")),
                    "mae_pct": fnum(band.get("mae_pct")),
                    "missed_upside_pct": fnum(band.get("missed_upside_pct")),
                    "avoided_loss_pct": fnum(band.get("avoided_loss_pct")),
                    "score": score,
                })
    return rows, warnings


def summarize(rows: list[dict[str, Any]]) -> dict[str, Any]:
    total = len(rows)
    touched = [r for r in rows if r["touched"] is True]
    missed = [r for r in rows if r["touched"] is False and r["missed_upside_pct"] is not None]
    avoided = [r for r in rows if r["touched"] is False and r["avoided_loss_pct"] is not None]
    holds = [r["hold_pct"] for r in touched if r["hold_pct"] is not None]
    maes = [r["mae_pct"] for r in touched if r["mae_pct"] is not None]
    scores = [r["score"] for r in rows if r["score"] is not None]
    missed_vals = [r["missed_upside_pct"] for r in missed if r["missed_upside_pct"] is not None]
    avoided_vals = [r["avoided_loss_pct"] for r in avoided if r["avoided_loss_pct"] is not None]
    wins = [h for h in holds if h > 0]
    breaks = [h for h in holds if h <= -1.5]
    return {
        "n": total,
        "touch_n": len(touched),
        "touch_rate": pct(len(touched), total),
        "miss_n": len(missed),
        "miss_rate": pct(len(missed), total),
        "avoid_n": len(avoided),
        "avoid_rate": pct(len(avoided), total),
        "hold_mean": mean(holds),
        "hold_median": median(holds),
        "mae_mean": mean(maes),
        "mae_worst": min(maes) if maes else None,
        "win_rate": pct(len(wins), len(holds)),
        "break_rate": pct(len(breaks), len(holds)),
        "missed_upside_mean": mean(missed_vals),
        "avoided_loss_mean": mean(avoided_vals),
        "zone_score_mean": mean(scores),
        "zone_score_median": median(scores),
    }


def grouped(rows: list[dict[str, Any]], keys: tuple[str, ...]) -> dict[tuple[Any, ...], list[dict[str, Any]]]:
    out: dict[tuple[Any, ...], list[dict[str, Any]]] = defaultdict(list)
    for r in rows:
        out[tuple(r.get(k) for k in keys)].append(r)
    return dict(out)


def print_table(title: str, groups: dict[tuple[Any, ...], list[dict[str, Any]]]) -> None:
    print("\n" + "=" * 110)
    print(title)
    print("=" * 110)
    print(
        f"{'Group':<28} {'Band':<14} {'n':>4} {'Touch':>8} {'Miss':>8} {'Avoid':>8} "
        f"{'HoldMean':>10} {'MAEAvg':>9} {'Win':>7} {'Break':>7} {'MissUp':>9} {'Score':>9}"
    )
    print("-" * 110)
    for key, sub in sorted(groups.items(), key=lambda kv: (str(kv[0]), kv[0])):
        summary = summarize(sub)
        group_label = " / ".join(str(x) for x in key[:-1]) if len(key) > 1 else "ALL"
        band = key[-1]
        print(
            f"{group_label:<28.28} {band:<14.14} {summary['n']:>4} "
            f"{summary['touch_rate']:>7.0f}% {summary['miss_rate']:>7.0f}% {summary['avoid_rate']:>7.0f}% "
            f"{fmt(summary['hold_mean'], width=8):>10} {fmt(summary['mae_mean'], width=7):>9} "
            f"{summary['win_rate']:>6.0f}% {summary['break_rate']:>6.0f}% "
            f"{fmt(summary['missed_upside_mean'], width=7):>9} {summary['zone_score_mean'] if summary['zone_score_mean'] is not None else 0:>9.2f}"
        )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--since", help="Only include date >= YYYY-MM-DD")
    parser.add_argument("--glob", default="memory/daily/*/verification.json")
    parser.add_argument("--json", action="store_true", help="Output summary JSON")
    parser.add_argument("--min-n", type=int, default=1, help="Minimum rows per printed group")
    args = parser.parse_args()

    files = sorted(glob.glob(args.glob))
    if args.since:
        files = [f for f in files if os.path.basename(os.path.dirname(f)) >= args.since]

    rows, warnings = load_rows(files)
    if args.min_n > 1:
        # Applied only to printed groups below; raw JSON keeps all rows through summaries.
        pass

    if args.json:
        by_band = {k[0]: summarize(v) for k, v in grouped(rows, ("band",)).items()}
        by_regime_band = {
            " / ".join(str(x) for x in k): summarize(v)
            for k, v in grouped(rows, ("regime", "band")).items()
        }
        print(json.dumps({
            "files": files,
            "rows": len(rows),
            "warnings": warnings,
            "by_band": by_band,
            "by_regime_band": by_regime_band,
        }, ensure_ascii=False, indent=2))
        return

    print(f"Scanned {len(files)} verification.json files -> {len(rows)} band observations")
    if warnings:
        print(f"\nWarnings ({len(warnings)}):")
        for w in warnings[:20]:
            print("  - " + w)

    by_band = {k: v for k, v in grouped(rows, ("band",)).items() if len(v) >= args.min_n}
    print_table("ENTRY BAND SHADOW BACKTEST — ALL", by_band)

    by_regime = {k: v for k, v in grouped(rows, ("regime", "band")).items() if len(v) >= args.min_n}
    print_table("ENTRY BAND SHADOW BACKTEST — BY REGIME", by_regime)

    by_strategy = {k: v for k, v in grouped(rows, ("strategy", "band")).items() if len(v) >= args.min_n}
    print_table("ENTRY BAND SHADOW BACKTEST — BY STRATEGY", by_strategy)

    print("\nNote: ZoneScore is useful only within the same regime/playbook and with enough forward samples.")


if __name__ == "__main__":
    main()
